import "./application.css";
import "init";
import "client/cable";
import "client/transfer";
import "components/page/page";
import "components/account/account";
import "components/balance/balance";
import "components/transfer-form/transfer-form";
import "components/transactions/transactions";
